apiVersion: v1
kind: Pod
metadata:
  name: resource-requesting
spec:
  containers:
    - name: resource-requesting
      image: nginx:latest
      resources:
        requests:
          "example.com/mock-plugin" : 1
        limits:
          "example.com/mock-plugin" : 1